name: 'Sync'

description: 'The workflow for syncing files to a public GCS bucket'

inputs:
  source_dir:
    required: true
  bucket_name:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Sync
      shell: bash
      run: |
        gsutil -m rsync -d -r ${{ inputs.source_dir }} gs://${{ inputs.bucket_name }}
        gsutil -m setmeta -h 'Cache-Control:public, max-age=31536000' gs://${{ inputs.bucket_name }}/**/*
