name: 'Test'

description: 'The test workflow for a Django app'

inputs:
  app_name:
    required: true
  conf_path:
    required: true
  django_version:
    required: true
  github_token:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e .
        pip install pycodestyle coverage coveralls==2.2.0
        sudo apt-get install -qq python-dev libxml2-dev libxmlsec1-dev

    - name: Upgrade Django Version
      shell: bash
      run: pip install "Django~=${{ inputs.django_version }}.0"

    - name: Setup Django
      shell: bash
      run: |
        django-admin startproject project .
        test -f ${{ inputs.conf_path }}/urls.py && cp ${{ inputs.conf_path }}/urls.py project/
        test -f ${{ inputs.conf_path }}/settings.py && cat ${{ inputs.conf_path }}/settings.py >> project/settings.py

    - name: Run Linters
      shell: bash
      run: pycodestyle ${{ inputs.app_name }}/

    - name: Run Migrations
      shell: bash
      run: python manage.py migrate

    - name: Run Tests
      shell: bash
      run: |
        python -m compileall ${{ inputs.app_name }}/
        coverage run --source=${{ inputs.app_name }}/ manage.py test ${{ inputs.app_name }}

    - name: Record Test Results
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: coveralls
