name: 'Publish'

description: 'The workflow for publishing an app to PyPi'

inputs:
  app_name:
    required: true
  tag_name:
    required: true
  api_token:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build
      run: |
        echo ${{ inputs.tag_name }} > ${{ inputs.app_name }}/VERSION
        python setup.py sdist bdist_wheel

    - name: Publish to PyPi
      env:
        TWINE_REPOSITORY: pypi
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ inputs.api_token }}
      run: twine upload dist/*
