name: 'CI/CD Context'

description: 'Generate CI/CD context values'

inputs:
  release_name:
    description: 'Release name used for image registry name'
    required: true
  commit_hash_length:
    description: 'Length of application commit hash used as image tag'
    required: false
    default: 7

outputs:
  json_context:
    description: "Serialized JSON context for this release"
    value: ${{ steps.context.outputs.json_context }}

runs:
  using: 'composite'

  steps:
    - name: CI/CD Context
      id: context
      shell: bash
      run: |
        echo "::group::Context"

        JSON_CONTEXT="{"

        export FULL_COMMIT_HASH="${{ github.sha }}"
        export COMMIT_HASH="${FULL_COMMIT_HASH:0:${{ inputs.commit_hash_length }}}"
        JSON_CONTEXT="${JSON_CONTEXT}\"commit_hash\": \"${COMMIT_HASH}\""
        # echo "::set-output name=commit_hash::${COMMIT_HASH}"
        echo "commit_hash = ${COMMIT_HASH}"

        export IMAGE_TAG="${{ inputs.release_name }}:$COMMIT_HASH"
        JSON_CONTEXT="${JSON_CONTEXT},\"image_tag\": \"${IMAGE_TAG}\""
        # echo "::set-output name=image_tag::${IMAGE_TAG}"
        echo "image_tag = ${IMAGE_TAG}"

        export GITHUB_REF="${{ github.ref }}"
        GIT_REPO_BRANCH=${GITHUB_REF#refs/heads/}
        JSON_CONTEXT="${JSON_CONTEXT},\"git_repo_branch\": \"${GIT_REPO_BRANCH}\""
        # echo "::set-output name=git_repo_branch::${GIT_REPO_BRANCH}"
        echo "git_repo_branch = ${GIT_REPO_BRANCH}"

        JSON_CONTEXT="${JSON_CONTEXT}}"

        echo "${JSON_CONTEXT}"

        echo "::endgroup::"

        echo "::set-output name=json_context::${JSON_CONTEXT}"
