name: 'CI/CD Context'

description: 'Generate CI/CD context values'

inputs:
  release_name:
    required: true

outputs:
  commit_hash:
    description: "Commit ID to bind commit through containerization and deployment"
    value: ${{ steps.context.outputs.commit_hash }}
  image_tag:
    description: "Docker image tag for deployment"
    value: ${{ steps.context.outputs.image_tag }}
  git_repo_branch:
    description: "Short repository branch name"
    value: ${{ steps.context.outputs.git_repo_branch }}

runs:
  using: 'composite'

  steps:
    - name: CI/CD Context
      id: context
      shell: bash
      run: |
        echo "::group::Context"

        export FULL_COMMIT_HASH="${{ github.sha }}"
        export COMMIT_HASH="${FULL_COMMIT_HASH:0:7}"
        echo "::set-output name=commit_hash::${COMMIT_HASH}"
        echo "set commit_hash to ${{ steps.context.commit_hash }}"

        echo "::set-output name=image_tag::${{ inputs.release_name }}:$COMMIT_HASH"
        echo "set image_tag to ${{ steps.context.image_tag }}"

        export GITHUB_REF="${{ github.ref }}"
        GIT_REPO_BRANCH=${GITHUB_REF#refs/heads/}
        echo "::set-output name=git_repo_branch::${GIT_REPO_BRANCH}"
        echo "set git_repo_branch to ${{ steps.context.git_repo_branch }}"

        echo "::endgroup::"
