name: 'CI/CD Context'

description: 'Generate CI/CD context values'

inputs:
  release_name:
    required: true

outputs:
  commit_hash:
    description: "Commit ID to bind commit through containerization and deployment"
    value: ${{ steps.commit-hash.outputs.commit_hash }}
  image_tag:
    description: "Docker image tag for deployment"
    value: ${{ steps.image-tag.outputs.image_tag }}
  git_repo_branch:
    description: "Short repository branch name"
    value: ${{ steps.git-repo-branch.outputs.git_repo_branch }}

runs:
  using: 'composite'

  steps:
    - name: Commit Hash
      id: commit-hash
      shell: bash
      run: |
        export FULL_COMMIT_HASH="${{ github.sha }}"
        export COMMIT_HASH="${FULL_COMMIT_HASH:0:7}"
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        echo "::set-output name=commit_hash::${COMMIT_HASH}"

    - name: Image Tag
      id: image-tag
      shell: bash
      run: |
        echo "IMAGE_TAG=${{ inputs.release_name }}:$COMMIT_HASH" >> $GITHUB_ENV
        echo "::set-output name=image_tag::${IMAGE_TAG}"

    - name: Git Repository Branch Name
      id: git-repo-branch
      shell: bash
      run: |
        export GITHUB_REF="${{ github.ref }}"
        echo "GIT_REPO_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        echo "::set-output name=git_repo_branch::${GIT_REPO_BRANCH}"
