name: 'CI/CD Context'

description: 'Generate CI/CD context values'

inputs:
  release_name:
    description: 'Release name used for image registry name'
    required: true
  commit_hash_length:
    description: 'Length of application commit hash used as image tag'
    required: false
    default: 7

outputs:
  commit_hash:
    description: "Id used to trace commit through containerization and deployment"
    value: ${{ steps.context.outputs.commit_hash }}
  image_tag:
    description: "Docker image tag for deployment"
    value: ${{ steps.context.outputs.image_tag }}
  git_repo_branch:
    description: "Short Github repository branch name"
    value: ${{ steps.context.outputs.git_repo_branch }}

runs:
  using: 'composite'

  steps:
    - name: CI/CD Context
      id: context
      shell: bash
      run: |
        echo "::group::Context"

        export FULL_COMMIT_HASH="${{ github.sha }}"
        export COMMIT_HASH="${FULL_COMMIT_HASH:0:${{ inputs.commit_hash_length }}}"
        echo "::set-output name=commit_hash::${COMMIT_HASH}"
        echo "commit_hash = ${COMMIT_HASH}"

        export IMAGE_TAG="${{ inputs.release_name }}:$COMMIT_HASH"
        echo "::set-output name=image_tag::${IMAGE_TAG}"
        echo "image_tag = ${IMAGE_TAG}"

        export GITHUB_REF="${{ github.ref }}"
        GIT_REPO_BRANCH=${GITHUB_REF#refs/heads/}
        echo "::set-output name=git_repo_branch::${GIT_REPO_BRANCH}"
        echo "git_repo_branch = ${GIT_REPO_BRANCH}"

        echo "::endgroup::"
