name: 'Linters for Python apps'

description: 'Runs checks for python apps'

inputs:
  app_name:
    required: true
  exclude_paths:
    description: 'Paths excluded from style checks'
    required: false
    default: ''
  license:
    description: 'License to check'
    required: false
    default: 'Apache-2.0'
  copyright_owner:
    description: 'Copyright owner to check'
    required: false
    default: 'UW-IT, University of Washington'

runs:
  using: 'composite'

  steps:
    - name: Run Pycodestyle
      shell: bash
      run: >-
        if [[ ! -f "./Dockerfile" ]]; then
          pip install pycodestyle
          pycodestyle ${{ inputs.app_name }}/ --exclude=${{ inputs.exclude_paths }}
        fi

    - name: Check for License Headers
      shell: bash
      run: >-
        if [[ -f "./LICENSE" ]]; then
          LICENSE_ERR=$(find ${{ inputs.app_name }} -type f -size +0 -name "*.py"\
            -exec grep -PzL "# Copyright $(date +'%Y') ${{ inputs.copyright_owner }}\n# SPDX-License-Identifier: ${{ inputs.license }}" {} \;)
          if [[ ! -z $LICENSE_ERR ]]; then
            echo "Missing License or Copyright information:"
            echo "$LICENSE_ERR"
            exit 1
          fi
        fi
