name: 'Google Cloud Registry Push'

description: 'Tag and push image to GCR'

inputs:
  image_tag:
    description: 'Image tag to push to GCR'
    required: true
  gcp_json_key:
    description: 'Authentication key for GCP access'
    required: true
  gcp_project_id:
    description: 'GCP project containing registry'
    required: false
    default: 'uwit-mci-axdd'
  gcr_hostname:
    description: 'GCR hostname'
    required: false
    default: 'gcr.io'

outputs:
  gcr_tag:
    description: 'GCR image tag'
    value: ${{ steps.gcr-tag.outputs.gcr_tag }}

runs:
  using: 'composite'

  steps:
    - name: Verify GCP credentials
      shell: bash
      run: |
        if [[ -z "${{ inputs.gcp_json_key }}" ]]; then
          echo "Missing GCP credentials"
          exit 1
        fi

    - name: Docker Login
      id: gar-login
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.gcr_hostname }}
        username: _json_key
        password: ${{ inputs.gcp_json_key }}

    - name: Tag Image for GCR
      id: gcr-tag
      shell: bash
      run: |
        GCR_TAG=${{ inputs.gcr_hostname }}/${{ inputs.gcp_project_id }}/${{ inputs.image_tag }}
        docker tag "${{ inputs.image_tag }}" "$GCR_TAG"
        echo "::set-output name=gcr_tag::$GCR_TAG"

    - name: Push Image to GCR
      id: gcr-push
      shell: bash
      run: |
        docker push "${{ steps.gcr-tag.outputs.gcr_tag }}"
        echo "pushed ${{ steps.gcr-tag.outputs.gcr_tag }}"
